### ISSUE TITLE
Add OpenGraph API (`meta` elements) for prettier previews, especially on social media sharing

### ISSUE THREAD

**Issue by vitropy** [entropyxyz/entropy-docs#135]
- [ ] Bug
- [ ] Question
- [x] Improvement

**Steps to reproduce**:

When sharing a page from https://docs.entropy.xyz on various platforms, those platforms fetch previews of the content to display to users. Currently, those previews are all Docusaurus defaults. They should instead be Entropy-specific preview images such as logos and so on.

**Screenshot**:

<img width="594" alt="Screen Shot 2024-06-18 at Jun 18, 2 05 55 PM" src="https://github.com/entropyxyz/entropy-docs/assets/129776839/3832d37d-dc07-4948-a3b0-9b2398940215">

**Expected behavior**: 

Show the Entropy logo with a site-specific or, ideally, page-specific description.

**Comment by johnnymatthews** [comment]
Hmm, this is odd. I was pretty sure that that social image issue _was_ fixed in https://github.com/entropyxyz/entropy-docs/issues/109.

**Comment by johnnymatthews** [comment]
> maybe this is just a caching issue on Twitter's side?

Possibly. We'll just have to wait and see? If it continues to be an issue, we can reopen this issue and implement the custom head component from #136. That _might_ cause Tesla's Social Network Team to delete their cache.
