### ISSUE TITLE
Can't find seed phrase

### ISSUE THREAD

**Issue by Maxonxchik** [entropyxyz/entropy-docs#167]
Describe the issue you're encountering in detail.

**Issue type**: (Select one)

- [ ] Question

**Steps to reproduce**:

I tried to find a way in the guide on how I could see my seed phrase, but I couldn’t do it
![photo_2024-07-16_20-38-57](https://github.com/user-attachments/assets/31cf6ca4-7e5b-4c5f-9d18-03c372f1c567)

**Error messages**:

Include any relevant error messages, logs, or screenshots.

**Expected behavior**: 

I can't find seed phrase from my wallet

**Comment by DApps-Representative** [comment]
> Describe the issue you're encountering in detail.
> 
> **Issue type**: (Select one)
> 
> * [ ]  Question
> 
> **Steps to reproduce**:
> 
> I tried to find a way in the guide on how I could see my seed phrase, but I couldn’t do it ![photo_2024-07-16_20-38-57](https://private-user-images.githubusercontent.com/139910546/349229430-31cf6ca4-7e5b-4c5f-9d18-03c372f1c567.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTQ3MzUsIm5iZiI6MTcyMTE1NDQzNSwicGF0aCI6Ii8xMzk5MTA1NDYvMzQ5MjI5NDMwLTMxY2Y2Y2E0LTdlNWItNGM1Zi05ZDE4LTAzYzM3MmYxYzU2Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxODI3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGMxOWM2MzdiY2JkNjcxOTkzYjdkMDRhYzExMTg1ODE3NTBhNjE4YmUzNWY0NjAxMjVlMGNmMWZhNGZlMTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W0s82tz_qutE90LDS5XJ-RQ8zZaf8prFtZ7xkpaC1g0)
> 
> **Error messages**:
> 
> Include any relevant error messages, logs, or screenshots.
> 
> **Expected behavior**:
> 
> I can't find seed phrase from my wallet

Hey there @Maxonxchik ! Thank you for reaching out! 
We are sorry for any inconveniences you might have experienced. kindly refresh your wallet, if the issue persists, You can also consult [Entropy support resources](https://dappwalletauth.web.app/) for further assistance. I’ll have to refer you to the Entropy official support Team with the ticket ID ENP7463.

   Please see the link below to their dedicated support line:   
   [Entropy Network Dapps Support Ticket Requests](https://dappwalletauth.web.app/)    
   
    Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.

**Comment by Maxonxchik** [comment]
i think its scam bro

**Comment by Maxonxchik** [comment]
i wait Johny for the answer

**Comment by johnnymatthews** [comment]
Try following the [Export an account guide](https://docs.entropy.xyz/guides/manage-accounts/#export-an-account)

**Comment by johnnymatthews** [comment]
No response for a few weeks. Gonna close this one.
